# Generated by Django 5.2.9 on 2025-12-13 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glovo_app', '0002_address_address_name_en_address_address_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_store', to='glovo_app.store'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_store', to='glovo_app.store'),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_store', to='glovo_app.storemenu'),
        ),
        migrations.AlterField(
            model_name='review',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_store', to='glovo_app.store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_store', to='glovo_app.category'),
        ),
        migrations.AlterField(
            model_name='storemenu',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_menu_store', to='glovo_app.store'),
        ),
    ]
